### ISSUE TITLE
Have a way to pass in or give access to some shared_state across modules

### ISSUE THREAD

**Issue by awsomearvinder** [pcparadise/discordbot#10]
Namely, we need a way to pass around configuration and the likes between modules.

**Comment by lukadd16** [comment]
Apologies for bumping this issue after it having already been closed, but why not just sub-class [`commands.Bot`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html?highlight=commands%20bot#discord.ext.commands.Bot) in `main.py` and assign `config` to an instance variable of this sub-class? Given that we'd be sub-classing `commands.Bot` + the fact that `bot` is already passed into each Cog's constructor, this instance variable would then be accessible by every Cog.

Doing it this way seems a lot more intuitive to me compared to the current implementation (of passing in config to each cog's setup function). Just some food for thought.

**Comment by awsomearvinder** [comment]
Honestly - I didn't think about that and I kind of like it. My main programming language dosen't have inheritance, so I never really considered using it in that way.

**Comment by lukadd16** [comment]
I can work on this if you don't mind (I've done it before in another bot so it'll be easy to implement here).

**Comment by awsomearvinder** [comment]
Go for it, don't forget to change the examples too.
