### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by awsomearvinder** [pcparadise/discordbot#20]
We need a database. This database should have the following properties:

It should be easy to transfer data even after we add new fields / information. 
It should be easy to generate some sort of "setup" script with some test data in the repository.
Above all the database needs some form of documentation on how it's laid out. The "setup" script can act as that documentation, but something like SQL would be better then something like mongodb because of that. 

I'll get to it eventually, but I'm fine with someone else spearheading the issue too if they want it done faster.

**Comment by QuaKe8782** [comment]
https://pypi.org/project/SQLAlchemy/

**Comment by QuaKe8782** [comment]
w/ SQLite or PostgreSQL

**Comment by awsomearvinder** [comment]
We wouldn't be using PostgreSQL for this.
> It should be easy to generate some sort of "setup" script with some test data in the repository.

As far as I'm concerned the fact that you have to setup PostgreSQL beforehand goes against this point. SQLite is what I was thinking with a seperate (python? actual SQL file?) that sets up a database, and then throws test data in said database.

**Comment by QuaKe8782** [comment]
fair enough. sqlite is enough for this purpose anyways.
