### ISSUE TITLE
Bump Discord.py to latest version

### ISSUE THREAD

**Issue by lukadd16** [pcparadise/discordbot#24]
Any reason why discord.py is pinned to 1.5.0? For example, 1.6.0 introduced support for [replies](https://user-images.githubusercontent.com/58280822/116961063-480c1c80-ac70-11eb-86f0-69db328dd0ca.png), 1.7.0 added support for Stage Channels, plus the usual bug fixes that come with newer versions.

Latest version is 1.7.2, you can see the changelog [here](https://discordpy.readthedocs.io/en/stable/whats_new.html).

**Comment by awsomearvinder** [comment]
None really, I'm almost always willing to accept bumps to the direct dependencies, although I don't want to bump the dev tools as often (e.g. always only update black and pylint occasionally, and not to the latest version. The commit that does so should also make sure that the current code passes both pylint and black).

**Comment by awsomearvinder** [comment]
Figured it's worth adding in I want to support discordpy 2.0 as fast as possible as it comes out, as the sooner we do so the easier it probably is. I'd imagine the changes from our current code to 2.0 wouldn't be drastic.

**Comment by awsomearvinder** [comment]
Bumped to 1.7, closing.
