### ISSUE TITLE
Add dev-related dependencies to requirements.txt

### ISSUE THREAD

**Issue by lukadd16** [pcparadise/discordbot#25]
I know you already make it clear in the contributing file which versions of `black` and `pylint` should be used, but it'd be helpful if those dependencies could also be pinned either in the existing `requirements.txt` file or create a new file called `dev-requirements.txt` that will be used solely by developers when setting up their virtual environment (`pip install -r dev-requirements.txt`).

**Comment by awsomearvinder** [comment]
Yep! I've been meaning to do this myself. Another important aspect to it is that the CI should pull it's tools from here instead of being hardcoded as it is now. It should a trivial change to do honestly, and it's not really controversial in the slightest.

**Comment by awsomearvinder** [comment]
Fixed as of commit 07af998c3f1cdcb2a7b207a9e9e985e118ced866
