### ISSUE TITLE
Address server moderation concerns

### ISSUE THREAD

**Issue by Ganoodles** [pcparadise/discordbot#28]
Since we are planning on remaking the moderation commands anyways, I figured we might as well give some people the option to express what they would like to see changed, or possible ways to structure the moderation in the server.

**Comment by Ganoosh** [comment]
My idea is a 5 infraction system, such as what follows:
- Infraction 1 will result in a warning, that is all.
- Infraction 2 will also result in a hour mute.
- Infraction 3 will result in a day mute (This would result in rank demotion for any mod).
- Infraction 4 will result in another day mute.
- Infraction 5 is a ban.

All infractions would be wiped each month.
I do see some problems with this and am open to suggestions, or completely new ideas.

In an ideal world, mods aren't exempt from the rules, some bots such as mee6 ignore this, and don't allow mods to get banned, muted, or warned. This would not be the situation ideally.

Another thing to mention, Infraction 5 would be manually reviewed by an admin (or maybe lower roles if wanted)
