### ISSUE TITLE
Make config.ini not dependant on where you run the bot from

### ISSUE THREAD

**Issue by awsomearvinder** [pcparadise/discordbot#7]
Two possible methods for going about this is either going off of the path of the current script, or we could find a library similar to the 
[dirs-next](https://crates.io/crates/dirs-next) library in rust which finds the canonical "correct" place to read/write configs in on that particular OS.

Frankly - I'm fine with both approaches, but I *would* like it to be able to load it from within the file hierarchy of the source.

**Comment by Ganoosh** [comment]
We could find the absolute path from the relative path of `main.py` with the os module, and then store that in some sort of global constants, as mentioned in the comments of #6
